version: "3"
services:
  clientemqtt:
    build: ./clienteMqtt/
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazar√° por la env var SERVIDOR defineda en .env
      - TOPICO1=${TOPICO1}
      - TOPICO2=${TOPICO2}
      - PUBLICAR=${PUBLICAR}
    restart: unless-stopped